name: Build & Test & Publish

on: [push, workflow_dispatch]

jobs:
  build:
    uses: vostok/github.ci/.github/workflows/build.yml@master

  test:
    needs: build
    uses: vostok/github.ci/.github/workflows/test.yml@master
    with:
      frameworks: [net48, netcoreapp3.1, net5.0, net6.0]
           
  publish:
    needs: test
    uses: vostok/github.ci/.github/workflows/publish.yml@master